apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: ACCT_NUMBER.dkr.ecr.us-east-1.amazonaws.com/flask-app:1.0.0
        ports:
        - name: web
          containerPort: 80
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 256Mi
            cpu: 250m
        env: 
          - name: mysql_username 
            valueFrom: 
              secretKeyRef: 
                name: newsecret 
                key:  username
          - name: mysql_password 
            valueFrom: 
              secretKeyRef: 
                name: newsecret 
                key:  password
          - name: mysql_host 
            valueFrom: 
              secretKeyRef: 
                name: newsecret
                key:  host
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - general
